services:
  - type: web
    name: mundobike-api
    env: node
    plan: free
    buildCommand: npm ci --omit=dev
    startCommand: npm run server
    autoDeploy: true
    envVars:
      # CORS: allowed frontends (comma-separated)
      - key: FRONTEND_URL
        value: https://ciclomarket.ar

      # Supabase server credentials
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false

      # Resend SMTP
      # Prefer API (HTTP) to avoid SMTP egress issues on PaaS
      - key: RESEND_API_KEY
        sync: false
      - key: SMTP_FROM
        value: Ciclo Market <notificaciones@your-domain.com>
      # Renewal notifier (cron job to email sellers before expiry)
      - key: RENEWAL_NOTIFIER_ENABLED
        value: "true"
      - key: RENEWAL_REMINDER_TZ
        value: America/Argentina/Buenos_Aires
      - key: RENEWAL_REMINDER_CRON
        value: "0 * * * *"  # cada hora
      - key: RENEWAL_REMINDER_WINDOW_HOURS
        value: "24"         # buscar publicaciones que vencen en 24h
      - key: RENEWAL_REMINDER_COOLDOWN_HOURS
        value: "24"         # no reenviar dentro de 24h
      # Newsletter digest (últimos ingresos)
      - key: NEWSLETTER_DIGEST_ENABLED
        value: "true"
      - key: NEWSLETTER_DIGEST_TZ
        value: America/Argentina/Buenos_Aires
      - key: NEWSLETTER_DIGEST_CRON
        value: "0 21 * * 2" # martes 21:00

      # Review reminders (habilitar reseñas automáticamente y avisar 1 vez)
      - key: REVIEW_REMINDER_ENABLED
        value: "true"
      - key: REVIEW_REMINDER_TZ
        value: America/Argentina/Buenos_Aires
      - key: REVIEW_REMINDER_CRON
        value: "0 10 * * *"  # diario 10:00 (no reenvía)
      - key: REVIEW_REMINDER_BATCH_LIMIT
        value: "200"

      # Optional
      - key: SHARE_FALLBACK_IMAGE
        value: https://your-domain.com/og-preview.png
      - key: MERCADOPAGO_ACCESS_TOKEN
        sync: false
